name: Go Release Binaries

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: release ${{ matrix.goos }}/${{ matrix.goarch }} ${{ matrix.binary }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        binary: [syncd, web]
        platform: [linux-amd64, linux-arm7, darwin-amd64]
        include:
          - platform: linux-amd64
            goos: linux
            goarch: amd64
          - platform: linux-arm7
            goos: linux
            goarch: arm
            goarm: "7"
          - platform: darwin-amd64
            goos: darwin
            goarch: amd64
    steps:
      - uses: actions/checkout@v5
      - name: Set APP_VERSION environment
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev) >> ${GITHUB_ENV}
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goarm: ${{ matrix.goarm }}
          project_path: ./cmd/${{ matrix.binary }}
          binary_name: ${{ matrix.binary }}
          extra_files: config.yaml.example README.md
          ldflags: -X 'main.version=${{ env.APP_VERSION }}'
